### ISSUE TITLE
HTTP filter example

### ISSUE THREAD

**Issue by lizan** [lyft/envoy-filter-example#10]
Currently only L4 (TCP) filter are there, it would be nice to have HTTP filter example too.

**Comment by gabriel-sagula-hs** [comment]
Would be nice to have a more robust API documentation as well.

**Comment by lizan** [comment]
@mattklein123 @htuch Is anyone working on this? If no, @mtakigiku will take this.

**Comment by mattklein123** [comment]
No one is working on it. @lizan  @mtakigiku A++

Whatever you want to do is great, but I would probably start with something dead simple which just modifies some headers. Then we could have a different example that uses continuations maybe. (Or maybe even the example could set a a timer and continue after some period of time based on a header).

**Comment by htuch** [comment]
Fixed in #14.
